apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-nginx
  template:
    metadata:
      labels:
        app: gitops-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: gitops-nginx-service
spec:
  type: NodePort
  selector:
    app: gitops-nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30099
